apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
    component: scheduler
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: scheduler

  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: scheduler
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: "init"
        image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
        imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
        volumeMounts:
          - name: {{ .Release.Name }}-config
            mountPath: /root/airflow/airflow.cfg
            subPath: airflow.cfg
          - name: {{ .Release.Name }}-dags
            mountPath: "/root/airflow/dags/"
        env:
            {{ include "env" . | indent 12 }}

            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: admin-username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: admin-password
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: admin-email
        command:
          - "bash"
        args:
          - "-cx"
          - >
              cd `python -c "import site; print(site.getsitepackages()[0])"` &&
              airflow initdb && airflow upgradedb &&
              (
              airflow create_user
              --role Admin
              --username $ADMIN_USERNAME
              --password $ADMIN_PASSWORD
              --firstname $ADMIN_USERNAME
              --lastname $ADMIN_USERNAME
              --email $ADMIN_EMAIL || true
              )

      containers:
        - name: scheduler
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
          command:
            - "airflow"
          args:
            - "scheduler"
          ports:
            - name: http
              containerPort: {{ .Values.airflow.image.port }}
          env:
            {{ include "env" . | indent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-config
              mountPath: /root/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: {{ .Release.Name }}-dags
              mountPath: "/root/airflow/dags/"
            - name: {{ .Release.Name }}-logs
              mountPath: "/root/airflow/logs/"
      volumes:
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}
        - name: {{ .Release.Name }}-dags
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-dags
        - name: {{ .Release.Name }}-logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs
