#!/bin/bash

if [ "$CIRCLE_BRANCH" != "master" ]; then
    echo "I only update packages on commits to master"
    exit 0
fi

function commit_time {
    git log -1 --format=%ct "$1"
}

REPO_URL=https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/
CHARTS=$(find charts/* -type d -maxdepth 0)
UPDATED=n

for CHART in $CHARTS; do
    LAST_UPDATED_CHART_CODE=$(commit_time $CHART)
    LAST_UPDATED_CHART_PACKAGE=$(commit_time "$CHART-*")
    if [ $LAST_UPDATED_CHART_CODE -gt $LAST_UPDATED_CHART_PACKAGE ]; then
        echo "Packaging $CHART"
        helm package -d charts $CHART
        UPDATED=y
    fi
done

if [ $UPDATED == 'y' ]; then

    helm repo index --url $REPO_URL charts

    git config user.email $USER_EMAIL
    git config user.name $USER_NAME
    git add charts
    git commit -m "Updated packages and index (automated)"
    git push origin master

else
    echo "No updates"
fi
