apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  elasticsearch_url: {{ .Values.elasticsearch.url | b64enc | quote }}
  elasticsearch_user: {{ .Values.elasticsearch.user | b64enc | quote }}
  elasticsearch_password: {{ .Values.elasticsearch.password | b64enc | quote }}
  logstash_user: {{ .Values.logstash.user | b64enc | quote }}
  logstash_password: {{ .Values.logstash.password | b64enc | quote }}
