apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "aws-login.fullname" . }}
  labels:
    app: {{ template "aws-login.name" . }}
    chart: {{ template "aws-login.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "aws-login.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "aws-login.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          env:
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "aws-login.fullname" . }}
                  key: AUTH0_DOMAIN
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "aws-login.fullname" . }}
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "aws-login.fullname" . }}
                  key: AUTH0_CLIENT_SECRET
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "aws-login.fullname" . }}
                  key: AUTH0_CALLBACK_URL
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "aws-login.fullname" . }}
                  key: COOKIE_SECRET
            - name: AWS_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "aws-login.fullname" . }}
                  key: AWS_ACCOUNT_ID
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: {{ template "aws-login.fullname" . }}
                  key: ENV
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
