apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "fullname" .}}"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "{{ template "fullname" . }}"
      annotations:
        iam.amazonaws.com/role: "{{ .Values.AWS.IAMRole }}"
    spec:
      serviceAccountName: "{{ template "fullname" . }}"
      containers:
        - name: api
          image: "{{ .Values.API.Image.Repository }}:{{ .Values.API.Image.Tag }}"
          imagePullPolicy: "{{ .Values.API.Image.PullPolicy }}"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: ALLOWED_HOSTS
              value: "*"
            - name: BUCKET_REGION
              value: "{{ .Values.AWS.DefaultRegion }}"
            - name: DB_HOST
              value: {{ if .Values.tags.branch -}}
                  "{{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}"
                {{- else -}}
                  "{{ .Values.postgresql.postgresHost }}"
                {{- end }}
            - name: DB_NAME
              value: "{{ .Values.postgresql.postgresDatabase }}"
            - name: DB_USER
              value: "{{ .Values.postgresql.postgresUser }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ if .Values.tags.branch -}}
                  name: "{{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}"
                  {{- else -}}
                  name: "{{ template "fullname" . }}"
                  {{- end }}
                  key: postgres-password
            - name: DEBUG
              value: "{{ .Values.API.Environment.DEBUG }}"
            - name: DJANGO_SETTINGS_MODULE
              value: "control_panel_api.settings"
            - name: ELASTICSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: ELASTICSEARCH_HOST
            - name: ELASTICSEARCH_PORT
              value: "{{ .Values.API.Environment.ELASTICSEARCH_PORT }}"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: ELASTICSEARCH_PASSWORD
            - name: ENABLE_K8S_RBAC
              value: "{{ .Values.API.Environment.ENABLE_K8S_RBAC }}"
            - name: ENV
              value: "{{ .Values.API.Environment.ENV }}"
            - name: IAM_ARN_BASE
              value: "{{ .Values.API.Environment.IAM_ARN_BASE }}"
            - name: K8S_WORKER_ROLE_NAME
              value: "{{ .Values.API.Environment.K8S_WORKER_ROLE_NAME }}"
            - name: LOGS_BUCKET_NAME
              value: "{{ .Values.API.Environment.LOGS_BUCKET_NAME }}"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: OIDC_CLIENT_ID
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: OIDC_DOMAIN
            - name: OIDC_AUTH_EXTENSION_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: OIDC_AUTH_EXTENSION_URL
            - name: SAML_PROVIDER
              value: "{{ .Values.API.Environment.SAML_PROVIDER }}"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: SENTRY_DSN
            - name: NFS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: NFS_HOSTNAME
            - name: TOOLS_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: TOOLS_DOMAIN
            - name: RSTUDIO_AUTH_CLIENT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: RSTUDIO_AUTH_CLIENT_DOMAIN
            - name: RSTUDIO_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: RSTUDIO_AUTH_CLIENT_ID
            - name: RSTUDIO_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ template "fullname" . }}"
                  key: RSTUDIO_AUTH_CLIENT_SECRET
          readinessProbe:
            httpGet:
              path: /auth/login
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
