#!/bin/bash

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# Checks that the remote URL belongs to an approved Github organisation
exec 1>&2

allowed_orgs=(moj-analytical-services ministryofjustice)

remote="$1"
url="$2"

# extract github org or username from repo URL
org=$(
    echo $url | \
    sed -E 's|^(git@\|https://)github.com([:/])([a-zA-Z0-9_-]+)/.+$|\3|g'
)

in_allowed_orgs=false
for i in "${allowed_orgs[@]}"; do
    if [[ "$i" == "$org" ]]; then
        in_allowed_orgs=true;
    fi
done

if ! $in_allowed_orgs; then
    echo "
You are attempting to push to a remote owned by \"${org}\".

Only repositories owned by the following GitHub organisations are permitted as
push targets by default:

$(printf '%s\n' "${allowed_orgs[@]}")
    "

    exec < /dev/tty
    while true; do
        read -p "Do you wish to push to remote '${org}' anyway? (Y/n) " yn
        if [ "$yn" = "" ]; then
            yn='N'
        fi
        case $yn in
          [Yy] )
            exit 0;;
          [Nn] )
            echo -e "Push aborted.";
            exit 1;;
          * )
            echo -e "Please answer y or n for yes or no.";;
        esac
    done
fi
