#!/bin/bash
#
# Prevents large files from being committed

# Redirect output to stderr.
exec 1>&2

FILE_SIZE_LIMIT=5  # In MB
HAS_ERROR=""

for file in $(git diff --cached --name-only | sort | uniq); do
    file_size=$(du --apparent-size -m $(pwd)/$file | awk '{print $1}')
    if [ "$file_size" -ge $FILE_SIZE_LIMIT ]; then
        echo "$file is larger than the ${FILE_SIZE_LIMIT}MB limit."
        HAS_ERROR="1"
    fi
done

if [ "$HAS_ERROR" != "" ]; then
    exec < /dev/tty

    while true; do
        read -p "Do you wish to commit anyway? (Y/n) " yn
        if [ "$yn" = "" ]; then
            yn='N'
        fi
        case $yn in
          [Yy] )
            exit 0;;
          [Nn] )
            echo -e "\nCommit aborted. Please unstage oversize files with:\n\n\tgit reset FILENAME\n";
            exit 1;;
          * )
            echo -e "\nPlease answer y or n for yes or no.";;
        esac
    done
fi
