#!/bin/sh
#
# Prevents large files from being committed

# Redirect output to stderr.
exec 1>&2

FILE_SIZE_LIMIT=5  # In MB
HAS_ERROR=""

for file in $(git diff --cached --name-only | sort | uniq); do
    file_size=$(du --apparent-size -m $(pwd)/$file | awk '{print $1}')
    if [ "$file_size" -ge $FILE_SIZE_LIMIT ]; then
        echo "$file is larger than ${FILE_SIZE_LIMIT}MB."
        HAS_ERROR="1"
    fi
done

if [ "$HAS_ERROR" != "" ]; then
    echo "Can't commit due to oversize files, please unstage before committing." >&2
    exit 1
fi

exit 0
