apiVersion: batch/v1
kind: Job
metadata:
  name: org-pipeline-{{ .Values.github.org }}
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: set-pipeline
    spec:
      containers:
      - name: set-pipeline
        image: appropriate/curl:3.1
        imagePullPolicy: IfNotPresent
        env:
          - name: PIPELINE_NAME
            value: {{ .Values.concourse.pipeline_name }}
          - name: CONCOURSE_TEAM
            value: {{ .Values.concourse.team }}
          - name: CONCOURSE_TARGET_TEAM
            value: {{ .Values.concourse.target_team }}
          - name: CONCOURSE_URL
            value: {{ .Values.concourse.externalURL }}
          - name: FLY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fly-admin
                key: password
          - name: FLY_USERNAME
            valueFrom:
              secretKeyRef:
                name: fly-admin
                key: username
          - name: GITHUB_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: secrets
                key: github-access-token
          - name: GITHUB_ORG_RESOURCE_IMAGE
            value: {{ .Values.githubOrgResource.image }}
          - name: GITHUB_ORG_RESOURCE_TAG
            value: {{ .Values.githubOrgResource.tag }}
          - name: GITHUB_WEBHOOK_TOKEN
            valueFrom:
              secretKeyRef:
                name: secrets
                key: github-webhook-token
        command: [ "/bin/sh" ]
        args:
          - /scripts/set-pipeline.sh
          - {{ .Values.github.org }}
        volumeMounts:
          - name: scripts
            mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 500
